UdemyNLayerProject.Web/Models/ErrorViewModel.cs
using System;

namespace UdemyNLayerProject.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UdemyNLayerProject.Web/Controllers/CategoriesController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using UdemyNLayerProject.Web.ApiService;
using UdemyNLayerProject.Web.DTOs;
using UdemyNLayerProject.Web.Filters;

namespace UdemyNLayerProject.Web.Controllers
{
    public class CategoriesController : Controller
    {
        private CategoryApiService CategoryApiService { get; }

        private IMapper Mapper { get; }

        public CategoriesController(CategoryApiService categoryApiService, IMapper mapper)
        {
            Mapper = mapper;
            CategoryApiService = categoryApiService;
        }


        public async Task<IActionResult> Index()
        {
            var categories = await CategoryApiService.GetAllAsync();
            return View(Mapper.Map<IEnumerable<CategoryDto>>(categories));
        }

        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> Update(int id)
        {
            var category = await CategoryApiService.GetByIdAsync(id);
            return View(Mapper.Map<CategoryDto>(category));
        }

        [ServiceFilter(typeof(NotFoundFilter))]
        public async Task<IActionResult> Delete(int id)
        {
            await CategoryApiService.Delete(id);
            return RedirectToAction("Index");
        }


        [HttpPost]
        public async Task<IActionResult> Create(CategoryDto categoryDto)
        {
            await CategoryApiService.AddAsync(categoryDto);
            return RedirectToAction("Index");
        }


        [HttpPost]
        public async Task<IActionResult> Update(CategoryDto categoryDto)
        {
            await CategoryApiService.UpdateAsync(categoryDto);
            return RedirectToAction("Index");
        }
    }
}

UdemyNLayerProject.Web/Controllers/CopyCategoriesController.cs
// using System;
// using System.Collections;
// using System.Collections.Generic;
// using System.Threading.Tasks;
// using AutoMapper;
// using Microsoft.AspNetCore.Mvc;
// using UdemyNLayerProject.Core.Models;
// using UdemyNLayerProject.Core.Services;
// using UdemyNLayerProject.Web.DTOs;
// using UdemyNLayerProject.Web.Filters;
//
// namespace UdemyNLayerProject.Web.Controllers
// {
//     public class CopyCategoriesController : Controller
//     {
//         private ICategoryService CategoryService { get; }
//
//         private IMapper Mapper { get; }
//
//         public CategoriesController(ICategoryService categoryService, IMapper mapper)
//         {
//             CategoryService = categoryService;
//             Mapper = mapper;
//         }
//
//         public async Task<IActionResult> Index()
//         {
//             var categories = await CategoryService.GetAllAsync();
//             return View(Mapper.Map<IEnumerable<CategoryDto>>(categories));
//         }
//
//         public IActionResult Create()
//         {
//             return View();
//         }
//
//         [HttpPost]
//         public async Task<IActionResult> Create(CategoryDto categoryDto)
//         {
//             await CategoryService.AddAsync(Mapper.Map<Category>(categoryDto));
//             return RedirectToAction("Index");
//         }
//
//         public async Task<IActionResult> Update(int id)
//         {
//             var category = await CategoryService.GetByIdAsync(id);
//             return View(Mapper.Map<CategoryDto>(category));
//         }
//
//         [HttpPost]
//         public async Task<IActionResult> Update(CategoryDto categoryDto)
//         {
//             await CategoryService.UpdateAsync(Mapper.Map<Category>(categoryDto));
//             return RedirectToAction("Index");
//         }
//
//         [ServiceFilter(typeof(NotFoundFilter))]
//         public IActionResult Delete(int id)
//         {
//             CategoryService.Remove(CategoryService.GetByIdAsync(id).Result);
//             return RedirectToAction("Index");
//         }
//     }
// }

UdemyNLayerProject.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using UdemyNLayerProject.Web.DTOs;

namespace UdemyNLayerProject.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error(ErrorDto errorDto)
        {
            return View(errorDto);
            // return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

UdemyNLayerProject.Web/Controllers/ProductsController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using UdemyNLayerProject.Web.ApiService;
using UdemyNLayerProject.Web.DTOs;
using UdemyNLayerProject.Web.Filters;

namespace UdemyNLayerProject.Web.Controllers
{
    public class ProductsController : Controller
    {
        private ProductApiService ProductApiService { get; }
        private IMapper Mapper { get; }

        public ProductsController( IMapper mapper, ProductApiService productApiService)
        {
            Mapper = mapper;
            ProductApiService = productApiService;
        }
        
        
        public async Task<IActionResult> Index()
        {
            var products = await ProductApiService.GetAllAsync();
            return View(Mapper.Map<IEnumerable<ProductDto>>(products));
        }
        
        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> Update(int id)
        {
            var product = await ProductApiService.GetByIdAsync(id);
            return View(Mapper.Map<ProductDto>(product));
        }

        [ServiceFilter(typeof(NotFoundFilter))]
        public async Task<IActionResult> Delete(int id)
        {
            await ProductApiService.Delete(id);
            return RedirectToAction("Index");
        }


        [HttpPost]
        public async Task<IActionResult> Create(ProductDto productDto)
        {
            await ProductApiService.AddAsync(productDto);
            return RedirectToAction("Index");
        }


        [HttpPost]
        public async Task<IActionResult> Update(ProductDto productDto)
        {
            await ProductApiService.UpdateAsync(productDto);
            return RedirectToAction("Index");
        }


    }
}

UdemyNLayerProject.Web/Views/Categories/Create.cshtml
@model CategoryDto

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Kategori Ekleme</h2>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Categories">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name">Kategori Adı</label>
                <input class="form-control" asp-for="Name" placeholder="Kategori Adı"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Ekle" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

UdemyNLayerProject.Web/Views/Categories/Index.cshtml
@model IEnumerable<CategoryDto>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Kategoriler</h2>
<a class="btn btn-primary mb-1" asp-action="Create">Kategori Ekle</a>
<table class="table table-bordered">
    <thead>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>İşlemler</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var category in Model)
    {
        <tr>
            <td>@category.Id</td>
            <td>@category.Name</td>
            <td style="width: 160px">
                <a class="btn btn-outline-primary" asp-action="Update" asp-controller="Categories" asp-route-id="@category.Id">Güncelle</a>
                <a class="btn btn-outline-danger" 
                   OnClientClick="javascript:return confirm('Güncellemek istediğinize emin misiniz?')"
                   asp-action="Delete" asp-controller="Categories" asp-route-id="@category.Id">Sil</a>
            </td>
        </tr>
    }
    </tbody>
</table>

UdemyNLayerProject.Web/Views/Categories/Update.cshtml
@model CategoryDto

@{
    ViewBag.Title = "Kategori Güncelleme";
    Layout = "_Layout";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Update" asp-controller="Categories">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name">Kategori Adı</label>
                <input class="form-control" asp-for="Name" placeholder="Kategori Adı"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Güncelle" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

UdemyNLayerProject.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

UdemyNLayerProject.Web/Views/Products/Create.cshtml
@model ProductDto

@{
    ViewBag.Title = "Ürün Ekle";
    Layout = "_Layout";
}
<h1>@ViewBag.Title</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Products">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name">Ürün Adı</label>
                <input class="form-control" asp-for="Name" placeholder="Ürün Adı"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name">Stok Adet</label>
                <input class="form-control" asp-for="Stock" placeholder="Stok Adet"/>
                <span asp-validation-for="Stock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name">Fiyat</label>
                <input class="form-control" asp-for="Price" placeholder="Fiyat"/>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId">Kategorisi</label>
                <input class="form-control" min="0" asp-for="CategoryId" placeholder="Kategorisi"/>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Ekle" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

UdemyNLayerProject.Web/Views/Products/Index.cshtml
@model IEnumerable<ProductDto>

@{
    ViewBag.Title = "Ürünler";
    Layout = "_Layout";
}

<h2>@ViewBag.Title</h2>
<a class="btn btn-primary mb-1" asp-controller="Products" asp-action="Create">Ürün Ekle</a>
<table class="table table-bordered">
    <thead>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Price</th>
        <th>Category</th>
        <th>İşlemler</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var product in Model)
    {
        <tr>
            <td>@product.Id</td>
            <td>@product.Name</td>
            <td>@product.Price</td>
            <td>@product.CategoryId</td>
            <td style="width: 160px">
                <a class="btn btn-outline-primary" asp-action="Update" asp-controller="Products" 
                   asp-route-id="@product.Id">Güncelle</a>
                            <a class="btn btn-outline-danger" 
                               OnClientClick="javascript:return confirm('Güncellemek istediğinize emin misiniz?')"
                               asp-action="Delete" asp-controller="Products" asp-route-id="@product.Id">Sil</a>
                        </td>
        </tr>
    }
    </tbody>
</table>

UdemyNLayerProject.Web/Views/Products/Update.cshtml
@model ProductDto

@{
    ViewBag.Title = "Ürün Güncelle";
    Layout = "_Layout";
}
<h1>@ViewBag.Title</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update" asp-controller="Products">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name">Ürün Adı</label>
                <input class="form-control" asp-for="Name" placeholder="Ürün Adı"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stock">Stok Adet</label>
                <input class="form-control" asp-for="Stock" placeholder="Stok Adet"/>
                <span asp-validation-for="Stock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price">Fiyat</label>
                <input class="form-control" asp-for="Price" placeholder="Fiyat"/>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId">CategoryId</label>
                <input class="form-control" asp-for="CategoryId" placeholder="CategoryId"/>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Güncelle" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

UdemyNLayerProject.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - UdemyNLayerProject.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UdemyNLayerProject.Web</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="/categories">Kategoriler</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="/products">Ürünler</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - UdemyNLayerProject.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<partial name="_ValidationScriptsPartial"/>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>